# Node.js image
FROM node:14-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json ./

# Install application dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Define environment variable
ENV PORT 9090
ENV NODE_ENV development
ENV DB_USER x
ENV DATABASE_PASSWORD x
ENV DB_HOST x
ENV DB_PORT x
ENV DB_DATABASE x
ENV DATABASE_URL x
 
# Expose port for the running app
EXPOSE 3010

# Run the application
CMD ["node", "server.js"]
