apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9090
      nodePort: 32555
  type: LoadBalancer
